environ:
  IS_PROD: False

logging:
  python_log_level: DEBUG
  log4j_level: WARN

spark:
  application_name: DATAMART-COLLECTOR-APP

  jobs:
    users_info_datamart:
      DATE: 2022-03-12
      DEPTH: 10 
      SRC_PATH: /user/master/data/snapshots/geo-events/
      TGT_PATH: /user/prod/data/bi-hadoop/users-info-datamart

    location_zone_agg_datamart:
      DATE: 2022-03-12
      DEPTH: 10 
      SRC_PATH: /master/data/snapshots/geo-events/
      TGT_PATH: /user/prod/data/bi-hadoop/location-zone-agg-datamart

    friend_recommendation_datamart:
      DATE: 2022-03-12
      DEPTH: 10 
      SRC_PATH: /master/data/snapshots/geo-events/
      TGT_PATH: /user/prod/data/recommendations/friend-recommendation-datamart