environ:
  is_prod: true
  # Type of current evironment
  # Can be one of: ``dataproc``, ``airflow``, ``supervisor``, ``testing``
  type: airflow

logging:
  level:
    python: info
    java: warn

spark:
  application_name: datamart-collector-app

  jobs:
    collect_users_demographic_dm_job:
      date: 2022-04-26
      depth: 10
      src_path: s3a://data-ice-lake-05/messager-data/analytics/geo-events
      tgt_path: s3a://data-ice-lake-05/messager-data/analytics/tmp
      coords_path: s3a://data-ice-lake-05/messager-data/analytics/cities-coordinates

    collect_events_total_cnt_agg_wk_mnth_dm_job:
      date: 2022-04-26
      depth: 10
      src_path: s3a://data-ice-lake-05/messager-data/analytics/geo-events
      tgt_path: s3a://data-ice-lake-05/messager-data/analytics/tmp
      coords_path: s3a://data-ice-lake-05/messager-data/analytics/cities-coordinates

    collect_add_to_friends_recommendations_dm_job:
      date: 2022-04-26
      depth: 10
      src_path: s3a://data-ice-lake-05/messager-data/analytics/geo-events
      tgt_path: s3a://data-ice-lake-05/messager-data/analytics/tmp
      coords_path: s3a://data-ice-lake-05/messager-data/analytics/cities-coordinates
